<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.31">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>20&nbsp; Resultados de Terreno – Guía Técnica MRCT</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./integracion_validacion.html" rel="next">
<link href="./vuelo_drone.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-e1a5c8363afafaef2c763b6775fbf3ca.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-485d01fc63b59abcd3ee1bf1e8e2748d.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css">

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="style.css">
</head>

<body class="nav-sidebar floating slimcontent quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./trabajo_terreno.html">Trabajo en Terreno</a></li><li class="breadcrumb-item"><a href="./resultados_terreno.html"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Resultados de Terreno</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Guía Técnica MRCT</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Prefacio</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introducción</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./region_estudio.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Región de estudio y unidades de análisis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./insumos.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Insumos satelitales e índices espectrales</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inds_base.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Indicadores Base</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./vector_es.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Vector de Estado</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./trayectoria.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Trayectoria del estado</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./integracion_espacial.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Integración Territorial</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./sensibilidad.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Sensibilidad del Sistema</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./pt_resiliencia.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Potencial de Transición y Resiliencia</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./resultados.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Análisis de Resultados</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./conclusiones.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Conclusiones</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./trabajo_terreno.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Trabajo en Terreno</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./jerk.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Preevaluación de Cuencas</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cuencas_seleccionadas.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Cuencas Seleccionadas</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./logistica.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Logística y Traslados</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./condiciones_terreno.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Condiciones de Terreno y Climáticas</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./equipamiento.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Equipamiento</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./protocolo_levantamiento.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Protocolo de Levantamiento</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./fichas_cuencas.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Fichas de Cuencas</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./vuelo_drone.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Operación de Dron</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./resultados_terreno.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Resultados de Terreno</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./integracion_validacion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Integración y Validación</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Bibliografía</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active" data-toc-expanded="1">
    <h2 id="toc-title">Contenidos</h2>
   
  <ul>
  <li><a href="#sec-resumen-campana-terreno" id="toc-sec-resumen-campana-terreno" class="nav-link active" data-scroll-target="#sec-resumen-campana-terreno"><span class="header-section-number">20.1</span> Resumen de campaña</a></li>
  <li><a href="#sec-condiciones-levantamiento-terreno" id="toc-sec-condiciones-levantamiento-terreno" class="nav-link" data-scroll-target="#sec-condiciones-levantamiento-terreno"><span class="header-section-number">20.2</span> Condiciones de levantamiento</a></li>
  <li><a href="#sec-resultados-por-cuenca-terreno" id="toc-sec-resultados-por-cuenca-terreno" class="nav-link" data-scroll-target="#sec-resultados-por-cuenca-terreno"><span class="header-section-number">20.3</span> Resultados por cuenca</a></li>
  <li><a href="#sec-evidencia-visual-rid-terreno" id="toc-sec-evidencia-visual-rid-terreno" class="nav-link" data-scroll-target="#sec-evidencia-visual-rid-terreno"><span class="header-section-number">20.4</span> Evidencia visual por RID</a></li>
  <li><a href="#sec-contraste-ieo-res-terreno" id="toc-sec-contraste-ieo-res-terreno" class="nav-link" data-scroll-target="#sec-contraste-ieo-res-terreno"><span class="header-section-number">20.5</span> Contraste estadístico IEO-RES</a></li>
  <li><a href="#sec-sintesis-mediciones-terreno" id="toc-sec-sintesis-mediciones-terreno" class="nav-link" data-scroll-target="#sec-sintesis-mediciones-terreno"><span class="header-section-number">20.6</span> Síntesis de mediciones</a></li>
  <li><a href="#sec-coherencias-terreno" id="toc-sec-coherencias-terreno" class="nav-link" data-scroll-target="#sec-coherencias-terreno"><span class="header-section-number">20.7</span> Coherencias encontradas</a></li>
  <li><a href="#sec-inconsistencias-terreno" id="toc-sec-inconsistencias-terreno" class="nav-link" data-scroll-target="#sec-inconsistencias-terreno"><span class="header-section-number">20.8</span> Inconsistencias y tensiones interpretativas</a></li>
  <li><a href="#sec-lectura-esperado-encontrado" id="toc-sec-lectura-esperado-encontrado" class="nav-link" data-scroll-target="#sec-lectura-esperado-encontrado"><span class="header-section-number">20.9</span> Lectura metodológica de lo esperado y lo encontrado</a></li>
  <li><a href="#sec-limitaciones-campana-terreno" id="toc-sec-limitaciones-campana-terreno" class="nav-link" data-scroll-target="#sec-limitaciones-campana-terreno"><span class="header-section-number">20.10</span> Limitaciones de campaña</a></li>
  <li><a href="#sec-cierre-resultados-terreno" id="toc-sec-cierre-resultados-terreno" class="nav-link" data-scroll-target="#sec-cierre-resultados-terreno"><span class="header-section-number">20.11</span> Cierre de resultados</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./trabajo_terreno.html">Trabajo en Terreno</a></li><li class="breadcrumb-item"><a href="./resultados_terreno.html"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Resultados de Terreno</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Resultados de Terreno</span></h1>
<p class="subtitle lead">Validación empírica de la MRCT en Magallanes 2026</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Este capítulo consolida los resultados de la campaña de levantamiento territorial realizada en la Provincia de Magallanes durante junio de 2026. Su función es cerrar el ciclo iniciado en la selección de cuencas, el protocolo IEO y la planificación logística: contrastar la señal satelital de resiliencia operativa (<code>RES</code>) con evidencia directa observada en terreno.</p>
<p>La campaña no se interpreta como una verificación mecánica del modelo. Se entiende como una prueba de coherencia entre dos escalas de observación: la MRCT, construida desde series satelitales anuales y métricas multivariadas, y el Índice de Estado Observado (IEO), levantado en sitio mediante rúbrica de vegetación, humedad, perturbación antrópica y fragmentación. En ese sentido, los resultados son relevantes tanto por las coincidencias como por las diferencias encontradas.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Lectura general
</div>
</div>
<div class="callout-body-container callout-body">
<p>El contraste IEO-<code>RES</code> muestra una consistencia estadística alta para las cuencas comparables: <span class="math inline">r = 0{,}7869</span>, <span class="math inline">R^2 = 0{,}6192</span> y <span class="math inline">p = 0{,}0069</span> sobre 10 cuencas con valor satelital disponible. Esto valida la utilidad operativa de la MRCT como sistema de priorización, pero no elimina la necesidad de revisar escala, acceso, fecha de observación y condiciones locales en cada caso.</p>
</div>
</div>
<section id="sec-resumen-campana-terreno" class="level2" data-number="20.1">
<h2 data-number="20.1" class="anchored" data-anchor-id="sec-resumen-campana-terreno"><span class="header-section-number">20.1</span> Resumen de campaña</h2>
<p>La campaña se ejecutó en condiciones invernales severas, con jornadas de observación entre el 16 y el 18 de junio de 2026 y una ventana operativa general comprendida entre el 15 y el 19 de junio. El equipo base estuvo compuesto por John Treimun, Paula Altamirano y Denis Berroeta, con roles diferenciados de observación, operación de dron, navegación, registro y soporte logístico.</p>
<p>El diseño de levantamiento mantuvo una separación entre observación de terreno y conocimiento del modelo. El observador responsable de aplicar la rúbrica IEO no debía conocer los valores <code>RES</code>, jerk o clasificación MRCT antes de cerrar la ficha. Esta decisión metodológica es importante: reduce el riesgo de sesgo de confirmación y permite que la correlación posterior entre IEO y <code>RES</code> sea una prueba más exigente.</p>
<p>La cartera inicial contenía 17 cuencas preseleccionadas en <a href="cuencas_seleccionadas.html#tbl-cuencas-seleccionadas-detalle" class="quarto-xref">Tabla&nbsp;<span>13.2</span></a>. La campaña levantó 13 estaciones efectivas: 10 cuencas hidrográficas comparables con el modelo MRCT y 3 puntos urbanos o periurbanos usados como contraste territorial, pero sin valor <code>RES</code> comparable dentro del modelo de cuencas biofísicas.</p>
<div id="tbl-cobertura-campana-terreno" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-cobertura-campana-terreno-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;20.1: Síntesis de cobertura de la campaña de terreno.
</figcaption>
<div aria-describedby="tbl-cobertura-campana-terreno-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Grupo</th>
<th style="text-align: right;">Resultado de campaña</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Cuencas preseleccionadas para la campaña</td>
<td style="text-align: right;">17</td>
</tr>
<tr class="even">
<td>Estaciones medidas en terreno</td>
<td style="text-align: right;">13</td>
</tr>
<tr class="odd">
<td>Cuencas con comparación IEO-<code>RES</code></td>
<td style="text-align: right;">10</td>
</tr>
<tr class="even">
<td>Puntos urbanos o periurbanos sin <code>RES</code> comparable</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="odd">
<td>Cuencas de la cartera no visitadas en esta ventana</td>
<td style="text-align: right;">7</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Las cuencas comparables fueron <code>RID</code> 5263, 5623, 5624, 5294, 5247, 4996, 4982, 5257, 2205 y 1808. Las cuencas planificadas que no quedaron medidas en esta ventana fueron <code>RID</code> 5258, 1885, 1886, 3289, 5048, 5209 y 5626. Los puntos <code>RID</code> 0001, 2077 y 1928 corresponden a registros urbanos o de borde urbano donde el modelo de cuencas no entrega <code>RES</code> por dominancia de superficies impermeables o porque no corresponden a una cuenca biofísica comparable.</p>
</section>
<section id="sec-condiciones-levantamiento-terreno" class="level2" data-number="20.2">
<h2 data-number="20.2" class="anchored" data-anchor-id="sec-condiciones-levantamiento-terreno"><span class="header-section-number">20.2</span> Condiciones de levantamiento</h2>
<p>La campaña funcionó como una prueba de esfuerzo para el protocolo. Se levantó información durante el invierno austral, con baja radiación, nubosidad alta, presencia de nieve en algunos sectores, temperaturas superficiales bajo cero y vientos fuertes. En San Gregorio se registraron condiciones de operación particularmente exigentes para el dron, con velocidades reportadas entre 50 y 100 km/h en varias estaciones. En Punta Arenas y Laredo las condiciones de viento fueron más favorables, aunque la nubosidad alcanzó 90-100% en los registros urbanos y periurbanos.</p>
<p>Esta condición invernal importa metodológicamente. La MRCT usa señales satelitales anuales y no pretende reproducir una fotografía instantánea del sitio. Por lo tanto, una observación hecha en junio puede mostrar nieve, senescencia, humedad congelada o baja actividad vegetal que no necesariamente equivale al estado promedio anual. Aun así, el contraste estadístico fue alto, lo que sugiere que la señal <code>RES</code> conserva capacidad de discriminar condiciones biofísicas incluso bajo ruido estacional.</p>
<div id="tbl-condiciones-operativas-terreno" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-condiciones-operativas-terreno-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;20.2: Condiciones ambientales y operativas de las cuencas comparables con MRCT.
</figcaption>
<div aria-describedby="tbl-condiciones-operativas-terreno-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 23%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 23%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;"><code>RID</code></th>
<th>Fecha / hora</th>
<th>Viento y operación dron</th>
<th style="text-align: right;">Nubosidad</th>
<th>Observación operativa</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">5263</td>
<td>2026-06-16 / 11:35</td>
<td>Dron con dificultad, 60 km/h</td>
<td style="text-align: right;">1%</td>
<td>Condición ventosa pero registrable.</td>
</tr>
<tr class="even">
<td style="text-align: right;">5623</td>
<td>2026-06-16 / 12:32</td>
<td>Dron con mayor dificultad, 80 km/h</td>
<td style="text-align: right;">1%</td>
<td>Vuelo exigente; evidencia útil con cautela.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5624</td>
<td>2026-06-16 / 12:46</td>
<td>Dron con mucha dificultad, 100 km/h</td>
<td style="text-align: right;">1%</td>
<td>Caso crítico para imagen aérea estable.</td>
</tr>
<tr class="even">
<td style="text-align: right;">5294</td>
<td>2026-06-16 / 12:55</td>
<td>Dron con mayor dificultad, 80 km/h</td>
<td style="text-align: right;">1%</td>
<td>Levantamiento condicionado por viento.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5247</td>
<td>2026-06-16 / 13:45</td>
<td>Vuelo normal, 30 km/h</td>
<td style="text-align: right;">25%</td>
<td>Buena condición relativa.</td>
</tr>
<tr class="even">
<td style="text-align: right;">4996</td>
<td>2026-06-16 / 14:02</td>
<td>Dron con dificultad, 60 km/h</td>
<td style="text-align: right;">35%</td>
<td>Registro posible con limitación de viento.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">4982</td>
<td>2026-06-16 / 14:17</td>
<td>Dron con dificultad, 50 km/h</td>
<td style="text-align: right;">40%</td>
<td>Registro posible con limitación de viento.</td>
</tr>
<tr class="even">
<td style="text-align: right;">5257</td>
<td>2026-06-16 / 14:35</td>
<td>Dron con dificultad, 60 km/h</td>
<td style="text-align: right;">60%</td>
<td>Registro posible con nubosidad creciente.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2205</td>
<td>2026-06-16 / 14:50</td>
<td>Vuelo normal, 30 km/h</td>
<td style="text-align: right;">70%</td>
<td>Registro operativo aceptable.</td>
</tr>
<tr class="even">
<td style="text-align: right;">1808</td>
<td>2026-06-17 / 09:12</td>
<td>Vuelo normal, 10 km/h</td>
<td style="text-align: right;">100%</td>
<td>Condición favorable de viento; nubosidad total.</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
<section id="sec-resultados-por-cuenca-terreno" class="level2" data-number="20.3">
<h2 data-number="20.3" class="anchored" data-anchor-id="sec-resultados-por-cuenca-terreno"><span class="header-section-number">20.3</span> Resultados por cuenca</h2>
<p>La tabla siguiente resume la base comparable entre el IEO observado y la resiliencia operativa <code>RES</code> del modelo. El IEO se calculó con la misma lógica definida en <a href="protocolo_levantamiento.html#sec-formula-ieo" class="quarto-xref"><span>Section 17.4.2</span></a>: vegetación y humedad suman como atributos positivos, mientras perturbación y fragmentación actúan como vectores negativos.</p>
<div id="tbl-ieo-res-terreno" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ieo-res-terreno-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;20.3: Base de validación IEO-<code>RES</code> para cuencas hidrográficas comparables.
</figcaption>
<div aria-describedby="tbl-ieo-res-terreno-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 11%">
<col style="width: 8%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 8%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;"><code>RID</code></th>
<th>Comuna</th>
<th style="text-align: right;">V</th>
<th style="text-align: right;">H</th>
<th style="text-align: right;">P</th>
<th style="text-align: right;">F</th>
<th style="text-align: right;">IEO observado</th>
<th style="text-align: right;"><code>RES</code> modelo</th>
<th>Clave</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">5263</td>
<td>San Gregorio</td>
<td style="text-align: right;">2.0</td>
<td style="text-align: right;">2.0</td>
<td style="text-align: right;">4.0</td>
<td style="text-align: right;">3.0</td>
<td style="text-align: right;">0.3125</td>
<td style="text-align: right;">0.5593</td>
<td>O</td>
</tr>
<tr class="even">
<td style="text-align: right;">5623</td>
<td>San Gregorio</td>
<td style="text-align: right;">2.5</td>
<td style="text-align: right;">2.0</td>
<td style="text-align: right;">4.0</td>
<td style="text-align: right;">3.0</td>
<td style="text-align: right;">0.3438</td>
<td style="text-align: right;">0.4959</td>
<td>C</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5624</td>
<td>San Gregorio</td>
<td style="text-align: right;">2.0</td>
<td style="text-align: right;">2.0</td>
<td style="text-align: right;">4.5</td>
<td style="text-align: right;">3.0</td>
<td style="text-align: right;">0.2813</td>
<td style="text-align: right;">0.0335</td>
<td>J</td>
</tr>
<tr class="even">
<td style="text-align: right;">5294</td>
<td>San Gregorio</td>
<td style="text-align: right;">2.0</td>
<td style="text-align: right;">2.0</td>
<td style="text-align: right;">4.0</td>
<td style="text-align: right;">3.0</td>
<td style="text-align: right;">0.3125</td>
<td style="text-align: right;">0.0149</td>
<td>G</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5247</td>
<td>San Gregorio</td>
<td style="text-align: right;">2.5</td>
<td style="text-align: right;">3.0</td>
<td style="text-align: right;">3.5</td>
<td style="text-align: right;">3.0</td>
<td style="text-align: right;">0.4375</td>
<td style="text-align: right;">0.4720</td>
<td>M</td>
</tr>
<tr class="even">
<td style="text-align: right;">4996</td>
<td>San Gregorio</td>
<td style="text-align: right;">1.0</td>
<td style="text-align: right;">2.0</td>
<td style="text-align: right;">4.0</td>
<td style="text-align: right;">3.0</td>
<td style="text-align: right;">0.2500</td>
<td style="text-align: right;">0.0054</td>
<td>O</td>
</tr>
<tr class="odd">
<td style="text-align: right;">4982</td>
<td>San Gregorio</td>
<td style="text-align: right;">1.0</td>
<td style="text-align: right;">2.0</td>
<td style="text-align: right;">4.0</td>
<td style="text-align: right;">3.0</td>
<td style="text-align: right;">0.2500</td>
<td style="text-align: right;">0.0046</td>
<td>O</td>
</tr>
<tr class="even">
<td style="text-align: right;">5257</td>
<td>San Gregorio</td>
<td style="text-align: right;">2.0</td>
<td style="text-align: right;">2.0</td>
<td style="text-align: right;">3.5</td>
<td style="text-align: right;">3.0</td>
<td style="text-align: right;">0.3438</td>
<td style="text-align: right;">0.0093</td>
<td>O</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2205</td>
<td>Punta Arenas</td>
<td style="text-align: right;">2.0</td>
<td style="text-align: right;">3.0</td>
<td style="text-align: right;">3.5</td>
<td style="text-align: right;">3.0</td>
<td style="text-align: right;">0.4063</td>
<td style="text-align: right;">0.0021</td>
<td>O</td>
</tr>
<tr class="even">
<td style="text-align: right;">1808</td>
<td>Punta Arenas</td>
<td style="text-align: right;">5.0</td>
<td style="text-align: right;">4.0</td>
<td style="text-align: right;">2.0</td>
<td style="text-align: right;">2.0</td>
<td style="text-align: right;">0.8125</td>
<td style="text-align: right;">1.0000</td>
<td>K</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>El patrón principal es claro. Las cuencas con <code>RES</code> muy bajo tendieron a presentar IEO bajo o medio-bajo, con vegetación pobre a media, humedad limitada, perturbación antrópica moderada a alta y fragmentación visible. En contraste, <code>RID</code> 1808 mostró simultáneamente el mayor IEO observado y el valor máximo de <code>RES</code>, consistente con una señal de alta resiliencia operativa.</p>
<p>La relación no es perfecta, y no debe esperarse que lo sea. El IEO captura una condición local observada en una fecha específica y desde puntos accesibles. La MRCT sintetiza una trayectoria anual de cuenca completa. Aun así, la dirección general entre ambas mediciones es coherente y estadísticamente significativa.</p>
</section>
<section id="sec-evidencia-visual-rid-terreno" class="level2 page-columns page-full" data-number="20.4">
<h2 data-number="20.4" class="anchored" data-anchor-id="sec-evidencia-visual-rid-terreno"><span class="header-section-number">20.4</span> Evidencia visual por RID</h2>
<p>Las imágenes siguientes complementan la ficha y la tabla IEO-<code>RES</code>. Muestran el entorno accesible desde el cual se obtuvo el registro, por lo que sirven para documentar cobertura, infraestructura y condiciones visibles, pero no representan por sí solas el polígono completo de cada cuenca. Cada lectura visual se vincula brevemente con el resultado, sin reemplazar el IEO ni la señal anual del modelo.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset page-columns page-full">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true" aria-current="page">RID 2205</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false">RID 5257</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-3" role="tab" aria-controls="tabset-1-3" aria-selected="false">RID 5294</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-4-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-4" role="tab" aria-controls="tabset-1-4" aria-selected="false">RID 1808</a></li></ul>
<div class="tab-content page-columns page-full">
<div id="tabset-1-1" class="tab-pane active page-columns page-full" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<div id="fig-rid-2205-evidencia" class="quarto-float quarto-figure quarto-figure-center anchored page-columns page-full" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure page-columns page-full">
<div aria-describedby="fig-rid-2205-evidencia-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/RID-2205/1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-margin quarto-float-caption quarto-float-fig margin-caption" id="fig-rid-2205-evidencia-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;20.1: Vista aérea del entorno accesible de RID 2205: corredor vial pavimentado, obras de drenaje laterales, postes de tendido y una matriz continua de vegetación baja.
</figcaption>
</figure>
</div>
<p>La imagen muestra una ruta pavimentada que atraviesa una matriz abierta de vegetación baja. Se distinguen cunetas o zanjas paralelas al camino, postes de tendido y una franja de borde intervenida por la infraestructura vial. Hacia el exterior del corredor predomina una cobertura baja y relativamente continua, sin elementos arbóreos visibles en el encuadre. Esta evidencia contextualiza la observación de perturbación y fragmentación registradas para la cuenca, sin asumir que el punto de acceso describe toda su extensión. En relación con el IEO medio-bajo (0.4063) y el <code>RES</code> muy bajo (0.0021), la escena muestra presiones visibles de borde, pero no un colapso visual uniforme; esa diferencia es coherente con la tensión de escala e intensidad discutida para el sitio.</p>
</div>
<div id="tabset-1-2" class="tab-pane page-columns page-full" role="tabpanel" aria-labelledby="tabset-1-2-tab">
<div id="fig-rid-5257-evidencia" class="quarto-float quarto-figure quarto-figure-center anchored page-columns page-full" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure page-columns page-full">
<div aria-describedby="fig-rid-5257-evidencia-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/RID-5257/1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-margin quarto-float-caption quarto-float-fig margin-caption" id="fig-rid-5257-evidencia-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;20.2: Vista aérea del entorno accesible de RID 5257: pradera abierta con cercos, ganado, huellas de tránsito y sectores de humedad superficial junto al corredor vial.
</figcaption>
</figure>
</div>
<p>La imagen registra un paisaje de pradera abierta, delimitado por cercos y atravesado por un corredor vial. Se observan animales en pastoreo, huellas de tránsito sobre el terreno y pequeños sectores con agua o humedad superficial próximos al borde del camino. La cobertura es predominantemente baja y el uso ganadero es visible; estos rasgos aportan contexto a la condición intermedia de humedad y a la perturbación observada, sin convertir la fotografía en una medición de la cuenca completa. Junto con el IEO de 0.3438 y el <code>RES</code> de 0.0093, la imagen ayuda a explicar una condición observada baja pero no homogéneamente degradada: combina señales de uso y fragmentación con sectores que conservan humedad superficial.</p>
</div>
<div id="tabset-1-3" class="tab-pane page-columns page-full" role="tabpanel" aria-labelledby="tabset-1-3-tab">
<div id="fig-rid-5294-evidencia" class="quarto-float quarto-figure quarto-figure-center anchored page-columns page-full" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure page-columns page-full">
<div aria-describedby="fig-rid-5294-evidencia-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/RID-5294/1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-margin quarto-float-caption quarto-float-fig margin-caption" id="fig-rid-5294-evidencia-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;20.3: Vista aérea del entorno accesible de RID 5294: camino pavimentado, cercos longitudinales y cobertura baja discontinua en una planicie expuesta.
</figcaption>
</figure>
</div>
<p>La fotografía muestra una planicie expuesta con vegetación baja, un camino pavimentado y cercos paralelos a la ruta. En los bordes se aprecian superficies de suelo más desnudo o con cobertura rala, además de una geometría lineal asociada al corredor vial. La escena hace visible la proximidad entre la observación y la infraestructura de transporte; por ello, la evidencia debe leerse junto con la ficha de sitio y no como una caracterización total de la cuenca. La baja cobertura visible y el corredor lineal son compatibles con el IEO bajo (0.3125) y el <code>RES</code> muy bajo (0.0149); al mismo tiempo, la imagen recuerda que un valor crítico del modelo no equivale necesariamente a una imagen de deterioro total en un único punto de acceso.</p>
</div>
<div id="tabset-1-4" class="tab-pane page-columns page-full" role="tabpanel" aria-labelledby="tabset-1-4-tab">
<div id="fig-rid-1808-evidencia" class="quarto-float quarto-figure quarto-figure-center anchored page-columns page-full" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure page-columns page-full">
<div aria-describedby="fig-rid-1808-evidencia-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/RID-1808/1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-margin quarto-float-caption quarto-float-fig margin-caption" id="fig-rid-1808-evidencia-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;20.4: Vista aérea del entorno accesible de RID 1808: ladera con cobertura arbórea, parches de nieve, camino sinuoso y vista hacia el área urbana o costera al fondo.
</figcaption>
</figure>
</div>
<p>La imagen muestra una ladera con cobertura arbórea, parches de nieve y un camino sinuoso que desciende hacia un área urbanizada o costera visible al fondo. También se distingue una franja abierta en la ladera y la cercanía entre bosque, camino y ocupación del borde. En este encuadre se observan elementos coherentes con una cobertura más densa y húmeda que la de las praderas abiertas; la interpretación final sigue correspondiendo a la ficha y al IEO de la cuenca, no sólo a la fotografía. Esta lectura visual se alinea con el IEO más alto de la campaña (0.8125) y <code>RES = 1.0000</code>: el caso de control positivo conserva una cobertura arbórea continua en el encuadre, aun bajo condiciones invernales y junto a un camino de acceso.</p>
</div>
</div>
</div>
</section>
<section id="sec-contraste-ieo-res-terreno" class="level2" data-number="20.5">
<h2 data-number="20.5" class="anchored" data-anchor-id="sec-contraste-ieo-res-terreno"><span class="header-section-number">20.5</span> Contraste estadístico IEO-RES</h2>
<p>El contraste lineal entre IEO observado y <code>RES</code> modelo se calculó sobre las 10 cuencas con ambos datos disponibles. Los tres puntos urbanos o periurbanos sin <code>RES</code> no fueron incluidos, porque no pertenecen al mismo dominio de inferencia del modelo de cuencas.</p>
<div id="tbl-contraste-estadistico-ieo-res" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-contraste-estadistico-ieo-res-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;20.4: Resultados del contraste estadístico entre IEO observado y <code>RES</code> modelo.
</figcaption>
<div aria-describedby="tbl-contraste-estadistico-ieo-res-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 30%">
<col style="width: 40%">
<col style="width: 30%">
</colgroup>
<thead>
<tr class="header">
<th>Métrica</th>
<th style="text-align: right;">Valor</th>
<th>Lectura</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>N comparable</td>
<td style="text-align: right;">10</td>
<td>Muestra de cuencas con IEO y <code>RES</code>.</td>
</tr>
<tr class="even">
<td>Correlación de Pearson</td>
<td style="text-align: right;">0.7869</td>
<td>Asociación positiva alta entre observación y modelo.</td>
</tr>
<tr class="odd">
<td><span class="math inline">R^2</span></td>
<td style="text-align: right;">0.6192</td>
<td>Aproximadamente 62% de la variación del IEO queda explicada por <code>RES</code> en el ajuste lineal.</td>
</tr>
<tr class="even">
<td>Valor p</td>
<td style="text-align: right;">0.0069</td>
<td>Relación estadísticamente significativa bajo <span class="math inline">p &lt; 0.01</span>.</td>
</tr>
<tr class="odd">
<td>Error estándar</td>
<td style="text-align: right;">0.1194</td>
<td>Magnitud del desajuste esperado alrededor de la recta.</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Estos valores permiten sostener una validación empírica fuerte para el uso de la MRCT como herramienta de priorización territorial. La evidencia no prueba causalidad ni reemplaza el análisis ecológico de detalle, pero sí confirma que la resiliencia operativa estimada por el modelo se ordena de manera compatible con condiciones físicas observadas en terreno.</p>
</section>
<section id="sec-sintesis-mediciones-terreno" class="level2" data-number="20.6">
<h2 data-number="20.6" class="anchored" data-anchor-id="sec-sintesis-mediciones-terreno"><span class="header-section-number">20.6</span> Síntesis de mediciones</h2>
<p>La síntesis de mediciones muestra que el levantamiento produjo una base integrada suficiente para comparar cuencas en tres planos: condición biofísica observada, restricción operativa de campaña y señal satelital. Para el cierre del libro, la variable central es el IEO promedio por cuenca; las condiciones de viento, nubosidad y operación de dron se usan como metadatos de interpretación.</p>
<div id="tbl-sintesis-mediciones-terreno" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-sintesis-mediciones-terreno-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;20.5: Síntesis operativa de mediciones de terreno para integración MRCT.
</figcaption>
<div aria-describedby="tbl-sintesis-mediciones-terreno-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Dimensión</th>
<th>Resultado integrado</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Condición observada</td>
<td>IEO entre 0.2500 y 0.8125 en las cuencas comparables.</td>
</tr>
<tr class="even">
<td>Señal satelital</td>
<td><code>RES</code> entre 0.0021 y 1.0000.</td>
</tr>
<tr class="odd">
<td>Restricción de vuelo</td>
<td>Viento crítico en varias cuencas de San Gregorio; condición más favorable en Punta Arenas / Laredo.</td>
</tr>
<tr class="even">
<td>Comparabilidad</td>
<td>10 cuencas comparables con MRCT; 3 puntos urbanos o periurbanos registrados como evidencia territorial no comparable con <code>RES</code>.</td>
</tr>
<tr class="odd">
<td>Uso metodológico</td>
<td>Validación estadística, clasificación de consistencia y lectura de discrepancias.</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
<section id="sec-coherencias-terreno" class="level2" data-number="20.7">
<h2 data-number="20.7" class="anchored" data-anchor-id="sec-coherencias-terreno"><span class="header-section-number">20.7</span> Coherencias encontradas</h2>
<p>Las principales coherencias entre lo esperado por la MRCT y lo observado en terreno son las siguientes.</p>
<p>Primero, la dirección general de la señal fue correcta. Las cuencas clasificadas con resiliencia operativa muy baja se asociaron con IEO bajo, perturbación antrópica visible, fragmentación y menor vigor de cobertura. Esto es consistente con la lectura de <a href="pt_resiliencia.html#sec-resiliencia-operativa" class="quarto-xref"><span>Section 9.3</span></a>: <code>RES</code> no declara un estado ecológico absoluto, pero ordena unidades territoriales según presión de transición.</p>
<p>Segundo, los casos de resiliencia media se ubicaron en posiciones intermedias. <code>RID</code> 5247, 5623 y 5263 no mostraron condiciones tan críticas como las cuencas de <code>RES</code> cercano a cero, pero tampoco aparecieron como sitios de alta integridad. Esta gradación es importante porque confirma que el modelo no sólo separa extremos, sino que también captura estados intermedios.</p>
<p>Tercero, <code>RID</code> 1808 funcionó como caso de control positivo. El terreno mostró alta vegetación, humedad relevante, baja perturbación relativa y menor fragmentación, mientras el modelo entregó <code>RES = 1.0000</code>. La coincidencia es metodológicamente útil porque evita que la campaña sólo valide cuencas críticas; también prueba que la MRCT reconoce condiciones favorables.</p>
<p>Cuarto, la exclusión de puntos urbanos sin <code>RES</code> es coherente con el alcance del modelo. En superficies impermeabilizadas o urbanas consolidadas, la lógica de cuenca biofísica pierde comparabilidad directa. Que esos puntos aparezcan como <code>N/A</code> no es una falla de la MRCT, sino una delimitación correcta de su dominio de aplicación.</p>
</section>
<section id="sec-inconsistencias-terreno" class="level2" data-number="20.8">
<h2 data-number="20.8" class="anchored" data-anchor-id="sec-inconsistencias-terreno"><span class="header-section-number">20.8</span> Inconsistencias y tensiones interpretativas</h2>
<p>Las diferencias más relevantes no invalidan el modelo, pero sí afinan su lectura.</p>
<p>La primera tensión aparece en cuencas con IEO medio-bajo pero <code>RES</code> extremadamente bajo, como <code>RID</code> 2205, 5257 o 5294. En esos casos, el terreno no necesariamente mostró un colapso visual total, pero sí condiciones compatibles con presión: perturbación, fragmentación, baja cobertura o humedad parcial. La diferencia sugiere que <code>RES</code> puede estar capturando trayectoria, sensibilidad o alejamiento multivariado acumulado que no siempre se ve como deterioro extremo en una sola visita.</p>
<p>La segunda tensión se relaciona con la fecha de observación. La campaña se realizó en invierno, mientras la MRCT integra señales anuales. Nieve, senescencia, suelo congelado, baja luz y nubosidad pueden modificar la apariencia instantánea del paisaje. Por eso, una discrepancia puntual debe revisarse contra la serie temporal, el año crítico de jerk, la imagen satelital usada y la estacionalidad de la cobertura.</p>
<p>La tercera tensión es espacial. El punto accesible no siempre representa la cuenca completa. Varias cuencas fueron observadas desde bordes, caminos o sectores seguros de detención. En cuencas heterogéneas, el IEO local puede subestimar o sobreestimar procesos que la MRCT calcula para el polígono completo.</p>
<p>La cuarta tensión es logística. El viento condicionó la calidad y estabilidad del registro aéreo, especialmente en <code>RID</code> 5624. Esto no afecta necesariamente el IEO peatonal, pero sí reduce la capacidad de leer continuidad espacial, cauces, fragmentación y estructura de cobertura desde dron.</p>
</section>
<section id="sec-lectura-esperado-encontrado" class="level2" data-number="20.9">
<h2 data-number="20.9" class="anchored" data-anchor-id="sec-lectura-esperado-encontrado"><span class="header-section-number">20.9</span> Lectura metodológica de lo esperado y lo encontrado</h2>
<p>Antes de la campaña, la MRCT esperaba encontrar un conjunto de cuencas útil para contrastar tres situaciones: resiliencia alta, resiliencia media y colapso potencial o transición acelerada. También se esperaba que la validación no dependiera de una sola variable visible, sino de la combinación entre vegetación, humedad, perturbación y fragmentación.</p>
<p>Lo encontrado confirma esa expectativa general. La campaña no produjo una correspondencia perfecta punto a punto, pero sí una relación fuerte entre el ordenamiento satelital y la condición observada. En términos prácticos, la MRCT acertó en la pregunta más importante para planificación: dónde mirar primero y qué sitios merecen revisión prioritaria.</p>
<p>La inconsistencia más valiosa es conceptual: un <code>RES</code> bajo no siempre se ve en terreno como una imagen simple de degradación absoluta. Puede expresarse como presión acumulada, fragmentación, pérdida de humedad, trayectoria acelerada, contraste con la línea base o sensibilidad a forzantes. Esto refuerza una idea ya planteada en el libro: la MRCT no debe leerse como sentencia visual, sino como sistema de preguntas territorialmente trazables.</p>
</section>
<section id="sec-limitaciones-campana-terreno" class="level2" data-number="20.10">
<h2 data-number="20.10" class="anchored" data-anchor-id="sec-limitaciones-campana-terreno"><span class="header-section-number">20.10</span> Limitaciones de campaña</h2>
<p>La campaña deja cuatro limitaciones principales para la lectura final.</p>
<p>Primero, la muestra comparable es pequeña. Diez cuencas permiten una validación inicial sólida, pero no reemplazan una campaña ampliada con más comunas, estaciones y tipos de cobertura.</p>
<p>Segundo, la ventana temporal fue invernal. Esto es una fortaleza como prueba de esfuerzo, pero también impone cautela para interpretar vigor vegetal, nieve, agua superficial y temperatura de coberturas.</p>
<p>Tercero, no todas las cuencas preseleccionadas fueron visitadas. La priorización logística redujo la cartera inicial a un subconjunto efectivo; por lo tanto, las cuencas no visitadas deben mantenerse como candidatas para una segunda campaña o para validación remota complementaria.</p>
<p>Cuarto, las condiciones de viento afectaron la operación de dron. En general se obtuvo evidencia funcional, pero la calidad del registro aéreo fue variable y en <code>RID</code> 5624 el viento limitó la estabilización de cámara.</p>
</section>
<section id="sec-cierre-resultados-terreno" class="level2" data-number="20.11">
<h2 data-number="20.11" class="anchored" data-anchor-id="sec-cierre-resultados-terreno"><span class="header-section-number">20.11</span> Cierre de resultados</h2>
<p>El resultado central de la campaña es que la MRCT mostró consistencia empírica bajo condiciones difíciles. El modelo ordenó las cuencas de manera compatible con el estado observado y mantuvo una asociación estadísticamente significativa con el IEO, aun cuando el levantamiento se realizó en invierno, con vientos intensos y sobre una muestra operacionalmente acotada.</p>
<p>La conclusión metodológica no es que la MRCT reemplaza al terreno. Es lo contrario: el terreno confirma que la MRCT sirve para focalizar la observación, distinguir prioridades y formular hipótesis verificables. Las coincidencias fortalecen la confianza en el modelo; las diferencias entregan información para mejorar su interpretación, ajustar campañas futuras y evitar lecturas simplistas de una métrica que, por diseño, sintetiza procesos multivariados, espaciales y temporales.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./vuelo_drone.html" class="pagination-link" aria-label="Operación de Dron">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Operación de Dron</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./integracion_validacion.html" class="pagination-link" aria-label="Integración y Validación">
        <span class="nav-page-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Integración y Validación</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Copyright 2026, <a href="https://cit.uai.cl/">Centro de Inteligencia Territorial</a></p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>